config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'home#show'
  resources :tools
  resources :home, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tool.rb
# frozen_string_literal: true

class Tool < ApplicationRecord
  belongs_to :user
end

# == Schema Information
#
# Table name: tools
#
#  id          :integer          not null, primary key
#  brand_name  :string
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :trackable, :omniauthable

  has_many :tools
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show; end
end

app/controllers/tools_controller.rb
# frozen_string_literal: true

class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def new
    unless current_user.present?
      flash[:error] = 'Log in or Sign up to add a tool!'
      redirect_to new_user_session_path status: :see_other
    end

    @tool = Tool.new
  end

  def create
    return redirect_to tools_path unless current_user.present?

    @tool = Tool.new(tool_params)
    @tool.user = current_user

    if @tool.save
      redirect_to tools_path, notice: 'Tool added successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :brand_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<div class='w-full flex flex-col space-y-8'>
  <div class="flex justify-between">
    <div>
      <p>
        Welcome to the Catskill Community Tool Share
      </p>
      <p>
        Here are the current tools that we have available
      </p>
    </div>
    <%= render 'tools/add_tool_button' %>
  </div>
  <div>
    <%= turbo_frame_tag :tools_index, src: tools_path %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div 
  data-controller="notification"
  data-notification-delay-value="1500"
  class="transition transform duration-1000 hidden"
  data-transition-enter-from="opacity-0 -translate-y-6"
  data-transition-enter-to="opacity-100 translate-y-0"
  data-transition-leave-from="opacity-100 translate-y-0"
  data-transition-leave-to="opacity-0 -translate-y-6"
  >
  <% flash.each do |type, msg| %>
    <div class='w-full h-0 flex justify-center'>
      <% bg_class = type == 'notice' ? 'bg-emerald-300' : 'bg-pink-300' %>
      <div class='z-10 relative justify-between h-fit rounded-md items_center p-4 -my-8 mx-auto w-2/3 xl:w-1/3 <%= bg_class %>' data-turbo-temporary='true'>
        <button class='absolute top-1 right-3' data-action="notification#hide">&times;</button>
        <p class='text-sm xl:text-base py-2 w-full text-center font-semibold'>
          <%= msg %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="bg-lime-900 h-20 text-zinc-100 p-4 flex items-center">
  <nav class="mx-auto max-w-5xl w-full flex items-center justify-between">
    <div class="flex items-center gap-4">
      <%= link_to root_path do %>
        <div class="flex flex-col text-xl font-bold italic text-amber-50">
          <p>Catskill Community Tools</p>
        </div>
      <% end %>
      <div class="text-xs hidden sm:block ml-10 text-zinc-300">
        <p>From each according to ability</p>
        <p>To each according to need</p>
      </div>
    </div>
    <% if current_user.present? %>
      <%= button_to "Log Out", destroy_user_session_path, data:{ turbo: :false }, method: :delete, class: "text-zinc-300" %>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: "text-zinc-300" %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catskill Community Tools</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-yellow-50">
    <%= render "layouts/header" %>
    <%= turbo_frame_tag :flash do %>
      <%= render 'layouts/flash' %>
    <% end %>
    <main class="container mx-auto p-4 flex max-w-5xl">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tools/_add_tool_button.html.erb
<div>
  <%= link_to '+ Add Tool', new_tool_path, class: "text-sm whitespace-nowrap md:text-base cta-btn" %>
</div>

app/views/tools/index.html.erb
<div class="flex flex-col mx-auto w-full gap-4">
  <div class="flex justify-between">
    <h1 class='text-3xl font-bold'>Tools</h1>
    <%= render 'add_tool_button' %>
  </div>
  <%= turbo_frame_tag :tools_index do %>
    <% if @tools.any? %>
      <div class='text-sm lg:text-base overflow-x-auto'>
      <table class='w-full'>
        <thead class='text-left'>
          <tr>
            <th class='p-2 border border-slate-700'>Tool Name</th>
            <th class='p-2 border border-slate-700'>Tool Brand</th>
            <th class='p-2 border border-slate-700'>Owner Contact</th>
          </tr>
        </thead>
        <tbody>
          <% @tools.each do |tool| %>
            <tr>
              <td class='border border-slate-700 p-2'><%= tool.name %></td>
              <td class='border border-slate-700 p-2'><%= tool.brand_name %></td>
              <td class='border border-slate-700 p-2 underline'><%= mail_to tool.user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    <% else %>
      No tools yet!
    <% end %>
  <% end %>
</div>

app/views/tools/new.html.erb
<div class="w-full flex flex-col items-center space-y-4">
  <%= simple_form_for @tool do |f| %>
    <div class="flex flex-col items-center space-y-4">
      <%= f.input :name, label: 'Tool Name', input_html: {class: 'block'} %>
      <%= f.input :brand_name, label: 'Tool Brand', input_html: {class: 'block'} %>
      <%= f.submit class: 'w-3/5 btn' %>
    </div>
  <% end %>
</div>